# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from appwrite_server_python_sdk import schemas  # noqa: F401


class Identity(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Identity
    """


    class MetaOapg:
        required = {
            "providerAccessToken",
            "provider",
            "providerRefreshToken",
            "$createdAt",
            "providerEmail",
            "userId",
            "providerAccessTokenExpiry",
            "$id",
            "$updatedAt",
            "providerUid",
        }
        
        class properties:
            id = schemas.StrSchema
            created_at = schemas.StrSchema
            updated_at = schemas.StrSchema
            userId = schemas.StrSchema
            provider = schemas.StrSchema
            providerUid = schemas.StrSchema
            providerEmail = schemas.StrSchema
            providerAccessToken = schemas.StrSchema
            providerAccessTokenExpiry = schemas.StrSchema
            providerRefreshToken = schemas.StrSchema
            __annotations__ = {
                "$id": id,
                "$createdAt": created_at,
                "$updatedAt": updated_at,
                "userId": userId,
                "provider": provider,
                "providerUid": providerUid,
                "providerEmail": providerEmail,
                "providerAccessToken": providerAccessToken,
                "providerAccessTokenExpiry": providerAccessTokenExpiry,
                "providerRefreshToken": providerRefreshToken,
            }
    
    providerAccessToken: MetaOapg.properties.providerAccessToken
    provider: MetaOapg.properties.provider
    providerRefreshToken: MetaOapg.properties.providerRefreshToken
    providerEmail: MetaOapg.properties.providerEmail
    userId: MetaOapg.properties.userId
    providerAccessTokenExpiry: MetaOapg.properties.providerAccessTokenExpiry
    providerUid: MetaOapg.properties.providerUid
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["$id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["$createdAt"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["$updatedAt"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userId"]) -> MetaOapg.properties.userId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["provider"]) -> MetaOapg.properties.provider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["providerUid"]) -> MetaOapg.properties.providerUid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["providerEmail"]) -> MetaOapg.properties.providerEmail: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["providerAccessToken"]) -> MetaOapg.properties.providerAccessToken: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["providerAccessTokenExpiry"]) -> MetaOapg.properties.providerAccessTokenExpiry: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["providerRefreshToken"]) -> MetaOapg.properties.providerRefreshToken: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["$id", "$createdAt", "$updatedAt", "userId", "provider", "providerUid", "providerEmail", "providerAccessToken", "providerAccessTokenExpiry", "providerRefreshToken", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["$id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["$createdAt"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["$updatedAt"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userId"]) -> MetaOapg.properties.userId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["provider"]) -> MetaOapg.properties.provider: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["providerUid"]) -> MetaOapg.properties.providerUid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["providerEmail"]) -> MetaOapg.properties.providerEmail: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["providerAccessToken"]) -> MetaOapg.properties.providerAccessToken: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["providerAccessTokenExpiry"]) -> MetaOapg.properties.providerAccessTokenExpiry: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["providerRefreshToken"]) -> MetaOapg.properties.providerRefreshToken: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["$id", "$createdAt", "$updatedAt", "userId", "provider", "providerUid", "providerEmail", "providerAccessToken", "providerAccessTokenExpiry", "providerRefreshToken", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        providerAccessToken: typing.Union[MetaOapg.properties.providerAccessToken, str, ],
        provider: typing.Union[MetaOapg.properties.provider, str, ],
        providerRefreshToken: typing.Union[MetaOapg.properties.providerRefreshToken, str, ],
        providerEmail: typing.Union[MetaOapg.properties.providerEmail, str, ],
        userId: typing.Union[MetaOapg.properties.userId, str, ],
        providerAccessTokenExpiry: typing.Union[MetaOapg.properties.providerAccessTokenExpiry, str, ],
        providerUid: typing.Union[MetaOapg.properties.providerUid, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Identity':
        return super().__new__(
            cls,
            *args,
            providerAccessToken=providerAccessToken,
            provider=provider,
            providerRefreshToken=providerRefreshToken,
            providerEmail=providerEmail,
            userId=userId,
            providerAccessTokenExpiry=providerAccessTokenExpiry,
            providerUid=providerUid,
            _configuration=_configuration,
            **kwargs,
        )
