# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from appwrite_server_python_sdk import schemas  # noqa: F401


class Log(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Log
    """


    class MetaOapg:
        required = {
            "clientName",
            "ip",
            "clientVersion",
            "osName",
            "userName",
            "deviceName",
            "userId",
            "clientEngineVersion",
            "osCode",
            "mode",
            "clientEngine",
            "clientType",
            "osVersion",
            "clientCode",
            "countryCode",
            "deviceModel",
            "userEmail",
            "countryName",
            "time",
            "event",
            "deviceBrand",
        }
        
        class properties:
            event = schemas.StrSchema
            userId = schemas.StrSchema
            userEmail = schemas.StrSchema
            userName = schemas.StrSchema
            mode = schemas.StrSchema
            ip = schemas.StrSchema
            time = schemas.StrSchema
            osCode = schemas.StrSchema
            osName = schemas.StrSchema
            osVersion = schemas.StrSchema
            clientType = schemas.StrSchema
            clientCode = schemas.StrSchema
            clientName = schemas.StrSchema
            clientVersion = schemas.StrSchema
            clientEngine = schemas.StrSchema
            clientEngineVersion = schemas.StrSchema
            deviceName = schemas.StrSchema
            deviceBrand = schemas.StrSchema
            deviceModel = schemas.StrSchema
            countryCode = schemas.StrSchema
            countryName = schemas.StrSchema
            __annotations__ = {
                "event": event,
                "userId": userId,
                "userEmail": userEmail,
                "userName": userName,
                "mode": mode,
                "ip": ip,
                "time": time,
                "osCode": osCode,
                "osName": osName,
                "osVersion": osVersion,
                "clientType": clientType,
                "clientCode": clientCode,
                "clientName": clientName,
                "clientVersion": clientVersion,
                "clientEngine": clientEngine,
                "clientEngineVersion": clientEngineVersion,
                "deviceName": deviceName,
                "deviceBrand": deviceBrand,
                "deviceModel": deviceModel,
                "countryCode": countryCode,
                "countryName": countryName,
            }
    
    clientName: MetaOapg.properties.clientName
    ip: MetaOapg.properties.ip
    clientVersion: MetaOapg.properties.clientVersion
    osName: MetaOapg.properties.osName
    userName: MetaOapg.properties.userName
    deviceName: MetaOapg.properties.deviceName
    userId: MetaOapg.properties.userId
    clientEngineVersion: MetaOapg.properties.clientEngineVersion
    osCode: MetaOapg.properties.osCode
    mode: MetaOapg.properties.mode
    clientEngine: MetaOapg.properties.clientEngine
    clientType: MetaOapg.properties.clientType
    osVersion: MetaOapg.properties.osVersion
    clientCode: MetaOapg.properties.clientCode
    countryCode: MetaOapg.properties.countryCode
    deviceModel: MetaOapg.properties.deviceModel
    userEmail: MetaOapg.properties.userEmail
    countryName: MetaOapg.properties.countryName
    time: MetaOapg.properties.time
    event: MetaOapg.properties.event
    deviceBrand: MetaOapg.properties.deviceBrand
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["event"]) -> MetaOapg.properties.event: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userId"]) -> MetaOapg.properties.userId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userEmail"]) -> MetaOapg.properties.userEmail: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userName"]) -> MetaOapg.properties.userName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mode"]) -> MetaOapg.properties.mode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ip"]) -> MetaOapg.properties.ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["time"]) -> MetaOapg.properties.time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["osCode"]) -> MetaOapg.properties.osCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["osName"]) -> MetaOapg.properties.osName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["osVersion"]) -> MetaOapg.properties.osVersion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientType"]) -> MetaOapg.properties.clientType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientCode"]) -> MetaOapg.properties.clientCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientName"]) -> MetaOapg.properties.clientName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientVersion"]) -> MetaOapg.properties.clientVersion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientEngine"]) -> MetaOapg.properties.clientEngine: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientEngineVersion"]) -> MetaOapg.properties.clientEngineVersion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deviceName"]) -> MetaOapg.properties.deviceName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deviceBrand"]) -> MetaOapg.properties.deviceBrand: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deviceModel"]) -> MetaOapg.properties.deviceModel: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["countryCode"]) -> MetaOapg.properties.countryCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["countryName"]) -> MetaOapg.properties.countryName: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["event", "userId", "userEmail", "userName", "mode", "ip", "time", "osCode", "osName", "osVersion", "clientType", "clientCode", "clientName", "clientVersion", "clientEngine", "clientEngineVersion", "deviceName", "deviceBrand", "deviceModel", "countryCode", "countryName", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["event"]) -> MetaOapg.properties.event: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userId"]) -> MetaOapg.properties.userId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userEmail"]) -> MetaOapg.properties.userEmail: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userName"]) -> MetaOapg.properties.userName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mode"]) -> MetaOapg.properties.mode: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ip"]) -> MetaOapg.properties.ip: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["time"]) -> MetaOapg.properties.time: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["osCode"]) -> MetaOapg.properties.osCode: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["osName"]) -> MetaOapg.properties.osName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["osVersion"]) -> MetaOapg.properties.osVersion: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientType"]) -> MetaOapg.properties.clientType: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientCode"]) -> MetaOapg.properties.clientCode: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientName"]) -> MetaOapg.properties.clientName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientVersion"]) -> MetaOapg.properties.clientVersion: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientEngine"]) -> MetaOapg.properties.clientEngine: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientEngineVersion"]) -> MetaOapg.properties.clientEngineVersion: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deviceName"]) -> MetaOapg.properties.deviceName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deviceBrand"]) -> MetaOapg.properties.deviceBrand: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deviceModel"]) -> MetaOapg.properties.deviceModel: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["countryCode"]) -> MetaOapg.properties.countryCode: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["countryName"]) -> MetaOapg.properties.countryName: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["event", "userId", "userEmail", "userName", "mode", "ip", "time", "osCode", "osName", "osVersion", "clientType", "clientCode", "clientName", "clientVersion", "clientEngine", "clientEngineVersion", "deviceName", "deviceBrand", "deviceModel", "countryCode", "countryName", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        clientName: typing.Union[MetaOapg.properties.clientName, str, ],
        ip: typing.Union[MetaOapg.properties.ip, str, ],
        clientVersion: typing.Union[MetaOapg.properties.clientVersion, str, ],
        osName: typing.Union[MetaOapg.properties.osName, str, ],
        userName: typing.Union[MetaOapg.properties.userName, str, ],
        deviceName: typing.Union[MetaOapg.properties.deviceName, str, ],
        userId: typing.Union[MetaOapg.properties.userId, str, ],
        clientEngineVersion: typing.Union[MetaOapg.properties.clientEngineVersion, str, ],
        osCode: typing.Union[MetaOapg.properties.osCode, str, ],
        mode: typing.Union[MetaOapg.properties.mode, str, ],
        clientEngine: typing.Union[MetaOapg.properties.clientEngine, str, ],
        clientType: typing.Union[MetaOapg.properties.clientType, str, ],
        osVersion: typing.Union[MetaOapg.properties.osVersion, str, ],
        clientCode: typing.Union[MetaOapg.properties.clientCode, str, ],
        countryCode: typing.Union[MetaOapg.properties.countryCode, str, ],
        deviceModel: typing.Union[MetaOapg.properties.deviceModel, str, ],
        userEmail: typing.Union[MetaOapg.properties.userEmail, str, ],
        countryName: typing.Union[MetaOapg.properties.countryName, str, ],
        time: typing.Union[MetaOapg.properties.time, str, ],
        event: typing.Union[MetaOapg.properties.event, str, ],
        deviceBrand: typing.Union[MetaOapg.properties.deviceBrand, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Log':
        return super().__new__(
            cls,
            *args,
            clientName=clientName,
            ip=ip,
            clientVersion=clientVersion,
            osName=osName,
            userName=userName,
            deviceName=deviceName,
            userId=userId,
            clientEngineVersion=clientEngineVersion,
            osCode=osCode,
            mode=mode,
            clientEngine=clientEngine,
            clientType=clientType,
            osVersion=osVersion,
            clientCode=clientCode,
            countryCode=countryCode,
            deviceModel=deviceModel,
            userEmail=userEmail,
            countryName=countryName,
            time=time,
            event=event,
            deviceBrand=deviceBrand,
            _configuration=_configuration,
            **kwargs,
        )
