# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from appwrite_server_python_sdk import schemas  # noqa: F401


class TeamPrefs(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    Team preferences as a key-value object
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['Preferences']:
            return Preferences

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['Preferences'], typing.List['Preferences']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'TeamPrefs':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'Preferences':
        return super().__getitem__(i)

from appwrite_server_python_sdk.model.preferences import Preferences
