# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_server_python_sdk.paths.health_anti_virus.get import CheckAntivirusStatusRaw
from appwrite_server_python_sdk.paths.health_cache.get import CheckCacheStatusRaw
from appwrite_server_python_sdk.paths.health_db.get import CheckDbStatusRaw
from appwrite_server_python_sdk.paths.health_storage_local.get import CheckLocalStorageStatusRaw
from appwrite_server_python_sdk.paths.health_pubsub.get import CheckPubsubServerStatusRaw
from appwrite_server_python_sdk.paths.health.get import CheckServerStatusRaw
from appwrite_server_python_sdk.paths.health_storage.get import CheckStorageStatusRaw
from appwrite_server_python_sdk.paths.health_queue_functions.get import FunctionsQueueCountRaw
from appwrite_server_python_sdk.paths.health_queue_builds.get import GetBuildsQueueRaw
from appwrite_server_python_sdk.paths.health_queue_databases.get import GetDatabasesQueueRaw
from appwrite_server_python_sdk.paths.health_queue_deletes.get import GetDeletesQueueRaw
from appwrite_server_python_sdk.paths.health_queue_failed_name.get import GetFailedJobsRaw
from appwrite_server_python_sdk.paths.health_queue_mails.get import GetMailQueueSizeRaw
from appwrite_server_python_sdk.paths.health_queue_migrations.get import GetMigrationsQueueRaw
from appwrite_server_python_sdk.paths.health_queue_logs.get import GetQueueLogsRaw
from appwrite_server_python_sdk.paths.health_queue_messaging.get import GetQueueMessagingRaw
from appwrite_server_python_sdk.paths.health_queue.get import GetQueueStatusRaw
from appwrite_server_python_sdk.paths.health_queue_usage.get import GetQueueUsageRaw
from appwrite_server_python_sdk.paths.health_queue_usage_dump.get import GetQueueUsageDumpRaw
from appwrite_server_python_sdk.paths.health_certificate.get import GetSslCertRaw
from appwrite_server_python_sdk.paths.health_time.get import GetTimeInformationRaw
from appwrite_server_python_sdk.paths.health_queue_webhooks.get import GetWebhooksQueueRaw
from appwrite_server_python_sdk.paths.health_queue_certificates.get import QueueCertificatesGetRaw


class HealthApiRaw(
    CheckAntivirusStatusRaw,
    CheckCacheStatusRaw,
    CheckDbStatusRaw,
    CheckLocalStorageStatusRaw,
    CheckPubsubServerStatusRaw,
    CheckServerStatusRaw,
    CheckStorageStatusRaw,
    FunctionsQueueCountRaw,
    GetBuildsQueueRaw,
    GetDatabasesQueueRaw,
    GetDeletesQueueRaw,
    GetFailedJobsRaw,
    GetMailQueueSizeRaw,
    GetMigrationsQueueRaw,
    GetQueueLogsRaw,
    GetQueueMessagingRaw,
    GetQueueStatusRaw,
    GetQueueUsageRaw,
    GetQueueUsageDumpRaw,
    GetSslCertRaw,
    GetTimeInformationRaw,
    GetWebhooksQueueRaw,
    QueueCertificatesGetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
