# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_server_python_sdk.paths.teams_team_id_memberships.post import CreateMembershipRequest
from appwrite_server_python_sdk.paths.teams.post import CreateNewTeam
from appwrite_server_python_sdk.paths.teams_team_id_memberships_membership_id.delete import DeleteMembership
from appwrite_server_python_sdk.paths.teams_team_id.get import GetById
from appwrite_server_python_sdk.paths.teams_team_id_memberships_membership_id.get import GetMembership
from appwrite_server_python_sdk.paths.teams_team_id_prefs.get import GetPrefsById
from appwrite_server_python_sdk.paths.teams.get import GetUserTeams
from appwrite_server_python_sdk.paths.teams_team_id_memberships.get import ListMemberships
from appwrite_server_python_sdk.paths.teams_team_id.delete import RemoveTeamById
from appwrite_server_python_sdk.paths.teams_team_id_memberships_membership_id.patch import UpdateMembershipRoles
from appwrite_server_python_sdk.paths.teams_team_id_memberships_membership_id_status.patch import UpdateMembershipStatus
from appwrite_server_python_sdk.paths.teams_team_id.put import UpdateNameById
from appwrite_server_python_sdk.paths.teams_team_id_prefs.put import UpdatePrefsById
from appwrite_server_python_sdk.apis.tags.teams_api_raw import TeamsApiRaw


class TeamsApi(
    CreateMembershipRequest,
    CreateNewTeam,
    DeleteMembership,
    GetById,
    GetMembership,
    GetPrefsById,
    GetUserTeams,
    ListMemberships,
    RemoveTeamById,
    UpdateMembershipRoles,
    UpdateMembershipStatus,
    UpdateNameById,
    UpdatePrefsById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TeamsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TeamsApiRaw(api_client)
